
name: Run selenium test

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: windows 10 pro- 22h2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          cache: maven
      - uses: browser-actions/setup-edge@v1
      - run: mvn clean test
